export const GET_PRODUCTS = "GET_PRODUCTS";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CART_PRODUCT = "GET_CART_PRODUCT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
